/* global jsPDF XLSX */
// jsPDF, jspdf-autotable and XLSX are loaded via CDN scripts in index.html

export interface ExportMeta {
  companyName?: string;
  reportTitle?: string;
  generatedBy?: string;
  filters?: { label: string; value: string }[];
}

function getJsPDF() {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const w = window as any;
  if (w.jspdf) return w.jspdf.jsPDF;
  if (w.jsPDF) return w.jsPDF;
  throw new Error("jsPDF not loaded");
}

function getXLSX() {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const w = window as any;
  if (w.XLSX) return w.XLSX;
  throw new Error("XLSX not loaded");
}

export function exportPDF(
  title: string,
  columns: string[],
  rows: (string | number)[][],
  filename: string,
  meta?: ExportMeta,
) {
  const JsPDF = getJsPDF();
  const doc = new JsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const companyName = meta?.companyName ?? "BizPOS System";
  let y = 15;

  // Company name
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text(companyName, 14, y);
  y += 7;

  // Report title
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);
  doc.text(title, 14, y);
  y += 7;

  // Generated date
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, y);
  y += 6;

  // Generated by
  if (meta?.generatedBy) {
    doc.text(`Generated by: ${meta.generatedBy}`, 14, y);
    y += 6;
  }

  // Active filters
  if (meta?.filters && meta.filters.length > 0) {
    for (const f of meta.filters) {
      doc.text(`${f.label}: ${f.value}`, 14, y);
      y += 6;
    }
  }

  // Horizontal rule
  y += 2;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, pageWidth - 14, y);
  y += 4;

  // autoTable is patched onto the doc instance by the CDN plugin
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (doc as any).autoTable({
    head: [columns],
    body: rows.map((r) => r.map(String)),
    startY: y,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [37, 99, 235] },
    didDrawPage: (data: any) => {
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(`Page ${data.pageNumber}`, pageWidth - 20, pageHeight - 10);
    },
  });

  doc.save(filename);
}

export function exportExcel(
  filename: string,
  sheetName: string,
  headers: string[],
  rows: (string | number)[][],
  meta?: ExportMeta,
) {
  const XLSX = getXLSX();
  const companyName = meta?.companyName ?? "BizPOS System";
  const metaRows: (string | number)[][] = [];

  // Row 1: company name
  metaRows.push([companyName]);

  // Row 2: report title (use filename stem as fallback)
  const reportTitle =
    meta?.reportTitle ?? filename.replace(/\.xlsx$/, "").replace(/-/g, " ");
  metaRows.push([reportTitle]);

  // Row 3: generated date
  metaRows.push([`Generated: ${new Date().toLocaleString()}`]);

  // Row 4: generated by
  if (meta?.generatedBy) {
    metaRows.push([`Generated by: ${meta.generatedBy}`]);
  }

  // Filter rows
  if (meta?.filters && meta.filters.length > 0) {
    for (const f of meta.filters) {
      metaRows.push([`${f.label}: ${f.value}`]);
    }
  }

  // Blank separator row
  metaRows.push([]);

  const ws = XLSX.utils.aoa_to_sheet([
    ...metaRows,
    headers,
    ...rows.map((r) => r.map(String)),
  ]);

  // Auto column widths
  const allRows = [...metaRows, headers, ...rows];
  const colWidths = headers.map((_: string, colIdx: number) => {
    let max = 15;
    for (const row of allRows) {
      const cell = row[colIdx];
      if (cell != null) {
        const len = String(cell).length;
        if (len > max) max = len;
      }
    }
    return { wch: max };
  });
  ws["!cols"] = colWidths;

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  XLSX.writeFile(wb, filename);
}
