import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import articles from "@/data/helpArticles";
import { ChevronRight, Download, HelpCircle, X } from "lucide-react";
import { useCallback, useState } from "react";

interface PageHelpProps {
  pageId: string;
}

declare const window: Window & {
  jspdf?: {
    jsPDF: new (
      opts?: object,
    ) => {
      text: (t: string, x: number, y: number, opts?: object) => void;
      setFontSize: (n: number) => void;
      setFont: (f: string, style?: string) => void;
      setTextColor: (r: number, g?: number, b?: number) => void;
      setDrawColor: (r: number, g?: number, b?: number) => void;
      setFillColor: (r: number, g?: number, b?: number) => void;
      rect: (
        x: number,
        y: number,
        w: number,
        h: number,
        style?: string,
      ) => void;
      line: (x1: number, y1: number, x2: number, y2: number) => void;
      splitTextToSize: (text: string, maxWidth: number) => string[];
      internal: {
        pageSize: { getWidth: () => number; getHeight: () => number };
      };
      addPage: () => void;
      save: (filename: string) => void;
    };
  };
};

export default function PageHelp({ pageId }: PageHelpProps) {
  const [open, setOpen] = useState(false);
  const article = articles[pageId];

  const handleDownloadPDF = useCallback(() => {
    if (!article) return;
    const jsPDF = window.jspdf?.jsPDF;
    if (!jsPDF) {
      alert("PDF library not loaded. Please refresh the page and try again.");
      return;
    }

    const doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    const addPage = () => {
      doc.addPage();
      y = margin;
    };

    const checkY = (needed: number) => {
      if (y + needed > pageHeight - margin) addPage();
    };

    // Header bar
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageWidth, 18, "F");
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text("BizPOS System \u2014 Help & Documentation", margin, 12);
    doc.text(new Date().toLocaleDateString(), pageWidth - margin, 12, {
      align: "right",
    });
    y = 28;

    // Title
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(37, 99, 235);
    doc.text(article.title, margin, y);
    y += 8;

    // Summary
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(75, 85, 99);
    const summaryLines = doc.splitTextToSize(article.summary, contentWidth);
    for (const line of summaryLines) {
      checkY(6);
      doc.text(line as string, margin, y);
      y += 6;
    }
    y += 4;

    // Divider
    doc.setDrawColor(229, 231, 235);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Sections
    for (const section of article.sections) {
      checkY(14);
      // Section heading background
      doc.setFillColor(239, 246, 255);
      doc.rect(margin - 2, y - 5, contentWidth + 4, 10, "F");
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(37, 99, 235);
      doc.text(section.heading, margin, y);
      y += 8;

      // Content
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(31, 41, 55);
      const lines = doc.splitTextToSize(section.content, contentWidth);
      for (const line of lines) {
        checkY(6);
        doc.text(line as string, margin, y);
        y += 6;
      }
      y += 6;
    }

    // Footer on each page
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      "BizPOS System \u2014 Generated by Help Center",
      margin,
      pageHeight - 8,
    );

    doc.save(`BizPOS-Help-${article.id}.pdf`);
  }, [article]);

  if (!article) return null;

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        title={`Help: ${article.title}`}
        className="inline-flex items-center justify-center w-8 h-8 rounded-full text-blue-500 hover:text-blue-700 hover:bg-blue-50 transition-colors"
      >
        <HelpCircle className="w-5 h-5" />
      </button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="w-full max-w-[95vw] sm:max-w-2xl max-h-[90vh] overflow-y-auto p-0">
          {/* Sticky header */}
          <div className="sticky top-0 z-10 bg-white border-b px-6 py-4 flex items-start justify-between gap-4 rounded-t-lg">
            <div className="flex-1">
              <DialogHeader>
                <DialogTitle className="text-xl font-bold text-blue-700 flex items-center gap-2">
                  <HelpCircle className="w-5 h-5 text-blue-500" />
                  {article.title}
                </DialogTitle>
              </DialogHeader>
              <p className="text-sm text-gray-500 mt-1 pr-8">
                {article.summary}
              </p>
            </div>
          </div>

          {/* Content */}
          <div className="px-6 py-4 space-y-5">
            {article.sections.map((section) => (
              <div
                key={section.heading}
                className="rounded-lg border border-blue-100 bg-blue-50/40 overflow-hidden"
              >
                <div className="bg-blue-50 px-4 py-2 flex items-center gap-2">
                  <ChevronRight className="w-4 h-4 text-blue-500" />
                  <h3 className="font-semibold text-blue-800 text-sm">
                    {section.heading}
                  </h3>
                </div>
                <div className="px-4 py-3">
                  <p className="text-sm text-gray-700 leading-relaxed">
                    {section.content}
                  </p>
                </div>
              </div>
            ))}
          </div>

          {/* Sticky footer with download */}
          <div className="sticky bottom-0 bg-white border-t px-6 py-3 flex items-center justify-between rounded-b-lg">
            <p className="text-xs text-gray-400">BizPOS Help Center</p>
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={handleDownloadPDF}
                className="flex items-center gap-1.5 text-blue-600 border-blue-200 hover:bg-blue-50"
              >
                <Download className="w-4 h-4" />
                Download PDF
              </Button>
              <Button size="sm" variant="ghost" onClick={() => setOpen(false)}>
                <X className="w-4 h-4 mr-1" />
                Close
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
