/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Warehouse = IDL.Record({
  'name' : IDL.Text,
  'location' : IDL.Text,
});
export const Item = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Float64,
  'price' : IDL.Float64,
  'warehouse' : Warehouse,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const Customer = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : Address,
  'phone' : IDL.Text,
});
export const Supplier = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : Address,
  'phone' : IDL.Text,
});
export const Purchase = IDL.Record({
  'id' : IDL.Nat,
  'supplier' : Supplier,
  'item' : Item,
  'total_cost' : IDL.Float64,
  'quantity' : IDL.Float64,
});
export const PosItem = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'quantity' : IDL.Float64,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'total' : IDL.Float64,
  'items' : IDL.Vec(PosItem),
});
export const Contact = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : Address,
  'phone' : IDL.Text,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'payment_method' : IDL.Text,
  'reference_number' : IDL.Text,
  'payer' : Contact,
  'amount' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transaction_type' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Account = IDL.Record({
  'id' : IDL.Nat,
  'balance' : IDL.Float64,
  'name' : IDL.Text,
  'transactions' : IDL.Vec(Transaction),
});
export const Report = IDL.Record({
  'total_sales' : IDL.Float64,
  'total_accounts' : IDL.Float64,
  'name' : IDL.Text,
  'total_inventory' : IDL.Float64,
  'total_payments' : IDL.Float64,
  'total_purchases' : IDL.Float64,
});
export const Settings = IDL.Record({
  'name' : IDL.Text,
  'system_id' : IDL.Nat,
  'company' : Contact,
});
export const WarehouseKey = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBusinessData' : IDL.Func(
      [
        IDL.Vec(Warehouse),
        IDL.Vec(Warehouse),
        IDL.Vec(Item),
        IDL.Vec(Item),
        IDL.Vec(Customer),
        IDL.Vec(Customer),
        IDL.Vec(Supplier),
        IDL.Vec(Supplier),
        IDL.Vec(Purchase),
        IDL.Vec(Purchase),
        IDL.Vec(Order),
        IDL.Vec(Order),
        IDL.Vec(Payment),
        IDL.Vec(Payment),
        IDL.Vec(Account),
        IDL.Vec(Account),
        IDL.Vec(Report),
        IDL.Vec(Report),
        Settings,
        IDL.Vec(Settings),
      ],
      [],
      [],
    ),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Address), IDL.Vec(Contact)],
      [],
      [],
    ),
  'addInitialWarehouse' : IDL.Func([], [], []),
  'addItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, WarehouseKey],
      [],
      [],
    ),
  'addSupplier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Address), IDL.Vec(Contact)],
      [],
      [],
    ),
  'addWarehouse' : IDL.Func([WarehouseKey, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAccount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Vec(Transaction)],
      [],
      [],
    ),
  'createOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Vec(PosItem),
        IDL.Float64,
        IDL.Text,
        IDL.Vec(Order),
        Customer,
      ],
      [],
      [],
    ),
  'createPayment' : IDL.Func(
      [IDL.Nat, Contact, Contact, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createPurchase' : IDL.Func(
      [IDL.Nat, Item, Supplier, IDL.Float64, IDL.Float64, IDL.Vec(Purchase)],
      [],
      [],
    ),
  'deleteAccount' : IDL.Func([IDL.Nat], [], []),
  'deleteItem' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'deletePayment' : IDL.Func([IDL.Nat], [], []),
  'deletePurchase' : IDL.Func([IDL.Nat], [], []),
  'deleteWarehouse' : IDL.Func([WarehouseKey], [], []),
  'editAccount' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Vec(Transaction)],
      [],
      [],
    ),
  'editItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, WarehouseKey],
      [],
      [],
    ),
  'editOrder' : IDL.Func(
      [IDL.Nat, IDL.Vec(PosItem), IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'editPayment' : IDL.Func(
      [IDL.Nat, Contact, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'editPurchase' : IDL.Func(
      [IDL.Nat, Item, Supplier, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'editWarehouse' : IDL.Func([WarehouseKey, IDL.Text, IDL.Text], [], []),
  'getAccount' : IDL.Func([IDL.Nat], [Account], ['query']),
  'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
  'getAllWarehouses' : IDL.Func([], [IDL.Vec(Warehouse)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
  'getItem' : IDL.Func([IDL.Text], [Item], ['query']),
  'getItemsByWarehouse' : IDL.Func([WarehouseKey], [IDL.Vec(Item)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
  'getPurchase' : IDL.Func([IDL.Nat], [Purchase], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getSupplier' : IDL.Func([IDL.Text], [Supplier], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWarehouseById' : IDL.Func([WarehouseKey], [Warehouse], ['query']),
  'initializeWarehouseData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateSettings' : IDL.Func([IDL.Text, IDL.Nat, Contact], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Warehouse = IDL.Record({ 'name' : IDL.Text, 'location' : IDL.Text });
  const Item = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Float64,
    'price' : IDL.Float64,
    'warehouse' : Warehouse,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const Customer = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : Address,
    'phone' : IDL.Text,
  });
  const Supplier = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : Address,
    'phone' : IDL.Text,
  });
  const Purchase = IDL.Record({
    'id' : IDL.Nat,
    'supplier' : Supplier,
    'item' : Item,
    'total_cost' : IDL.Float64,
    'quantity' : IDL.Float64,
  });
  const PosItem = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'quantity' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'total' : IDL.Float64,
    'items' : IDL.Vec(PosItem),
  });
  const Contact = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : Address,
    'phone' : IDL.Text,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'payment_method' : IDL.Text,
    'reference_number' : IDL.Text,
    'payer' : Contact,
    'amount' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transaction_type' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Account = IDL.Record({
    'id' : IDL.Nat,
    'balance' : IDL.Float64,
    'name' : IDL.Text,
    'transactions' : IDL.Vec(Transaction),
  });
  const Report = IDL.Record({
    'total_sales' : IDL.Float64,
    'total_accounts' : IDL.Float64,
    'name' : IDL.Text,
    'total_inventory' : IDL.Float64,
    'total_payments' : IDL.Float64,
    'total_purchases' : IDL.Float64,
  });
  const Settings = IDL.Record({
    'name' : IDL.Text,
    'system_id' : IDL.Nat,
    'company' : Contact,
  });
  const WarehouseKey = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBusinessData' : IDL.Func(
        [
          IDL.Vec(Warehouse),
          IDL.Vec(Warehouse),
          IDL.Vec(Item),
          IDL.Vec(Item),
          IDL.Vec(Customer),
          IDL.Vec(Customer),
          IDL.Vec(Supplier),
          IDL.Vec(Supplier),
          IDL.Vec(Purchase),
          IDL.Vec(Purchase),
          IDL.Vec(Order),
          IDL.Vec(Order),
          IDL.Vec(Payment),
          IDL.Vec(Payment),
          IDL.Vec(Account),
          IDL.Vec(Account),
          IDL.Vec(Report),
          IDL.Vec(Report),
          Settings,
          IDL.Vec(Settings),
        ],
        [],
        [],
      ),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Address), IDL.Vec(Contact)],
        [],
        [],
      ),
    'addInitialWarehouse' : IDL.Func([], [], []),
    'addItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, WarehouseKey],
        [],
        [],
      ),
    'addSupplier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Address), IDL.Vec(Contact)],
        [],
        [],
      ),
    'addWarehouse' : IDL.Func([WarehouseKey, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAccount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Vec(Transaction)],
        [],
        [],
      ),
    'createOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Vec(PosItem),
          IDL.Float64,
          IDL.Text,
          IDL.Vec(Order),
          Customer,
        ],
        [],
        [],
      ),
    'createPayment' : IDL.Func(
        [IDL.Nat, Contact, Contact, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createPurchase' : IDL.Func(
        [IDL.Nat, Item, Supplier, IDL.Float64, IDL.Float64, IDL.Vec(Purchase)],
        [],
        [],
      ),
    'deleteAccount' : IDL.Func([IDL.Nat], [], []),
    'deleteItem' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'deletePayment' : IDL.Func([IDL.Nat], [], []),
    'deletePurchase' : IDL.Func([IDL.Nat], [], []),
    'deleteWarehouse' : IDL.Func([WarehouseKey], [], []),
    'editAccount' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Vec(Transaction)],
        [],
        [],
      ),
    'editItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, WarehouseKey],
        [],
        [],
      ),
    'editOrder' : IDL.Func(
        [IDL.Nat, IDL.Vec(PosItem), IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'editPayment' : IDL.Func(
        [IDL.Nat, Contact, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editPurchase' : IDL.Func(
        [IDL.Nat, Item, Supplier, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'editWarehouse' : IDL.Func([WarehouseKey, IDL.Text, IDL.Text], [], []),
    'getAccount' : IDL.Func([IDL.Nat], [Account], ['query']),
    'getAllAccounts' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllPurchases' : IDL.Func([], [IDL.Vec(Purchase)], ['query']),
    'getAllWarehouses' : IDL.Func([], [IDL.Vec(Warehouse)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [Customer], ['query']),
    'getItem' : IDL.Func([IDL.Text], [Item], ['query']),
    'getItemsByWarehouse' : IDL.Func(
        [WarehouseKey],
        [IDL.Vec(Item)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getPayment' : IDL.Func([IDL.Nat], [Payment], ['query']),
    'getPurchase' : IDL.Func([IDL.Nat], [Purchase], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getSupplier' : IDL.Func([IDL.Text], [Supplier], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWarehouseById' : IDL.Func([WarehouseKey], [Warehouse], ['query']),
    'initializeWarehouseData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateSettings' : IDL.Func([IDL.Text, IDL.Nat, Contact], [], []),
  });
};

export const init = ({ IDL }) => { return []; };