/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : bigint,
  'balance' : number,
  'name' : string,
  'transactions' : Array<Transaction>,
}
export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface Contact {
  'name' : string,
  'email' : string,
  'address' : Address,
  'phone' : string,
}
export interface Customer {
  'name' : string,
  'email' : string,
  'address' : Address,
  'phone' : string,
}
export interface Item {
  'code' : string,
  'name' : string,
  'quantity' : number,
  'price' : number,
  'warehouse' : Warehouse,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'total' : number,
  'items' : Array<PosItem>,
}
export interface Payment {
  'id' : bigint,
  'payment_method' : string,
  'reference_number' : string,
  'payer' : Contact,
  'amount' : number,
}
export interface PosItem {
  'code' : string,
  'name' : string,
  'quantity' : number,
  'price' : number,
}
export interface Purchase {
  'id' : bigint,
  'supplier' : Supplier,
  'item' : Item,
  'total_cost' : number,
  'quantity' : number,
}
export interface Report {
  'total_sales' : number,
  'total_accounts' : number,
  'name' : string,
  'total_inventory' : number,
  'total_payments' : number,
  'total_purchases' : number,
}
export interface Settings {
  'name' : string,
  'system_id' : bigint,
  'company' : Contact,
}
export interface Supplier {
  'name' : string,
  'email' : string,
  'address' : Address,
  'phone' : string,
}
export interface Transaction {
  'id' : bigint,
  'transaction_type' : string,
  'amount' : number,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Warehouse { 'name' : string, 'location' : string }
export type WarehouseKey = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBusinessData' : ActorMethod<
    [
      Array<Warehouse>,
      Array<Warehouse>,
      Array<Item>,
      Array<Item>,
      Array<Customer>,
      Array<Customer>,
      Array<Supplier>,
      Array<Supplier>,
      Array<Purchase>,
      Array<Purchase>,
      Array<Order>,
      Array<Order>,
      Array<Payment>,
      Array<Payment>,
      Array<Account>,
      Array<Account>,
      Array<Report>,
      Array<Report>,
      Settings,
      Array<Settings>,
    ],
    undefined
  >,
  'addCustomer' : ActorMethod<
    [string, string, string, Array<Address>, Array<Contact>],
    undefined
  >,
  'addInitialWarehouse' : ActorMethod<[], undefined>,
  'addItem' : ActorMethod<
    [string, string, number, number, WarehouseKey],
    undefined
  >,
  'addSupplier' : ActorMethod<
    [string, string, string, Array<Address>, Array<Contact>],
    undefined
  >,
  'addWarehouse' : ActorMethod<[WarehouseKey, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<
    [bigint, string, number, Array<Transaction>],
    undefined
  >,
  'createOrder' : ActorMethod<
    [bigint, Array<PosItem>, number, string, Array<Order>, Customer],
    undefined
  >,
  'createPayment' : ActorMethod<
    [bigint, Contact, Contact, number, string, string],
    undefined
  >,
  'createPurchase' : ActorMethod<
    [bigint, Item, Supplier, number, number, Array<Purchase>],
    undefined
  >,
  'deleteAccount' : ActorMethod<[bigint], undefined>,
  'deleteItem' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deletePayment' : ActorMethod<[bigint], undefined>,
  'deletePurchase' : ActorMethod<[bigint], undefined>,
  'deleteWarehouse' : ActorMethod<[WarehouseKey], undefined>,
  'editAccount' : ActorMethod<
    [bigint, string, number, Array<Transaction>],
    undefined
  >,
  'editItem' : ActorMethod<
    [string, string, number, number, WarehouseKey],
    undefined
  >,
  'editOrder' : ActorMethod<
    [bigint, Array<PosItem>, number, string],
    undefined
  >,
  'editPayment' : ActorMethod<
    [bigint, Contact, number, string, string],
    undefined
  >,
  'editPurchase' : ActorMethod<
    [bigint, Item, Supplier, number, number],
    undefined
  >,
  'editWarehouse' : ActorMethod<[WarehouseKey, string, string], undefined>,
  'getAccount' : ActorMethod<[bigint], Account>,
  'getAllAccounts' : ActorMethod<[], Array<Account>>,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllPurchases' : ActorMethod<[], Array<Purchase>>,
  'getAllWarehouses' : ActorMethod<[], Array<Warehouse>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], Customer>,
  'getItem' : ActorMethod<[string], Item>,
  'getItemsByWarehouse' : ActorMethod<[WarehouseKey], Array<Item>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getPayment' : ActorMethod<[bigint], Payment>,
  'getPurchase' : ActorMethod<[bigint], Purchase>,
  'getSettings' : ActorMethod<[], Settings>,
  'getSupplier' : ActorMethod<[string], Supplier>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWarehouseById' : ActorMethod<[WarehouseKey], Warehouse>,
  'initializeWarehouseData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSettings' : ActorMethod<[string, bigint, Contact], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];